<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxnU4oG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxnU4oG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxnU4oG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxnU4oG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxnU4oG\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxnU4oG',
    'container.build_id' => 'de8338af',
    'container.build_time' => 1607797169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxnU4oG');
