<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIWJMoxa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIWJMoxa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIWJMoxa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIWJMoxa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIWJMoxa\App_KernelDevDebugContainer([
    'container.build_hash' => 'IWJMoxa',
    'container.build_id' => 'dff98223',
    'container.build_time' => 1607882990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIWJMoxa');
